-- BilikGo database install script (mysql)
-- All tables + demo seed (password: Demo@123). Seed photos are generated by the app on first run.

CREATE TABLE IF NOT EXISTS users (
            id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL UNIQUE,
            phone VARCHAR(255) DEFAULT '',
            password_hash VARCHAR(255) NOT NULL,
            role VARCHAR(10) NOT NULL,
            status VARCHAR(10) NOT NULL DEFAULT 'active',
            tos_accepted_at DATETIME,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS listings (
            id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            owner_id INT UNSIGNED NOT NULL,
            title VARCHAR(255) NOT NULL,
            area VARCHAR(255) NOT NULL,
            city VARCHAR(255) NOT NULL,
            address VARCHAR(255) DEFAULT '',
            price INTEGER NOT NULL,
            listing_type VARCHAR(6) NOT NULL DEFAULT 'rent',
            min_tenure INTEGER NOT NULL DEFAULT 0,
            dep_months DECIMAL(4,1) NOT NULL DEFAULT 0,
            util_months DECIMAL(4,1) NOT NULL DEFAULT 0,
            fee_rm INTEGER NOT NULL DEFAULT 0,
            lat DOUBLE PRECISION,
            lng DOUBLE PRECISION,
            room_type VARCHAR(255) NOT NULL,
            property_type VARCHAR(255) NOT NULL,
            furnishing VARCHAR(255) NOT NULL,
            gender_pref VARCHAR(10) NOT NULL DEFAULT 'Any',
            amenities TEXT,
            description TEXT,
            image VARCHAR(255) DEFAULT '',
            status VARCHAR(10) NOT NULL DEFAULT 'active',
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_listing_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS swipes (
            id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            tenant_id INT UNSIGNED NOT NULL,
            listing_id INT UNSIGNED NOT NULL,
            direction VARCHAR(5) NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_swipe UNIQUE (tenant_id, listing_id),
            CONSTRAINT fk_swipe_tenant  FOREIGN KEY (tenant_id)  REFERENCES users(id)    ON DELETE CASCADE,
            CONSTRAINT fk_swipe_listing FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS password_resets (
            id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            user_id INT UNSIGNED NOT NULL,
            token VARCHAR(64) NOT NULL UNIQUE,
            expires_at DATETIME NOT NULL,
            used INTEGER NOT NULL DEFAULT 0,
            CONSTRAINT fk_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
            name VARCHAR(50) NOT NULL PRIMARY KEY,
            value VARCHAR(255) NOT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reports (
            id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            listing_id INT UNSIGNED NOT NULL,
            reporter_id INT UNSIGNED NOT NULL,
            reason VARCHAR(50) NOT NULL,
            details TEXT,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uq_report UNIQUE (listing_id, reporter_id),
            CONSTRAINT fk_report_listing FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE,
            CONSTRAINT fk_report_user FOREIGN KEY (reporter_id) REFERENCES users(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS images (
            id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            listing_id INTEGER,
            sort INTEGER NOT NULL DEFAULT 0,
            mime VARCHAR(30) NOT NULL,
            data MEDIUMBLOB NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---- seed: users (terms pre-accepted for demo accounts) ----
INSERT INTO users (name,email,phone,password_hash,role,tos_accepted_at) VALUES ('Site Admin','admin@bilikgo.test','012-0000001','$2y$10$7FT0oqX6DMlC023nFOrAJu4ALlN6vM4/8mKHebb2RypCXioHSKiUG','admin','2026-06-12 19:26:39');
INSERT INTO users (name,email,phone,password_hash,role,tos_accepted_at) VALUES ('Aiman Properties','owner@bilikgo.test','012-0000002','$2y$10$7FT0oqX6DMlC023nFOrAJu4ALlN6vM4/8mKHebb2RypCXioHSKiUG','owner','2026-06-12 19:26:39');
INSERT INTO users (name,email,phone,password_hash,role,tos_accepted_at) VALUES ('Mei Ling Homes','owner2@bilikgo.test','012-0000003','$2y$10$7FT0oqX6DMlC023nFOrAJu4ALlN6vM4/8mKHebb2RypCXioHSKiUG','owner','2026-06-12 19:26:39');
INSERT INTO users (name,email,phone,password_hash,role,tos_accepted_at) VALUES ('Demo Tenant','tenant@bilikgo.test','012-0000004','$2y$10$7FT0oqX6DMlC023nFOrAJu4ALlN6vM4/8mKHebb2RypCXioHSKiUG','tenant','2026-06-12 19:26:39');

-- ---- seed: listings ----
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (2,'Cozy medium room near MRT Cheras','Cheras','Kuala Lumpur',650,'rent','Medium Room','Condominium','Fully furnished','Any','Wi-Fi,Air-conditioning,Washing machine,Near MRT/LRT,Pool,Gym','5 min walk to MRT Taman Mutiara. Utilities included, friendly housemates, move-in ready.','image.php?id=1',12,2,0.5,200,3.085,101.748);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (2,'Master room with bathroom, Bangsar South','Bangsar South','Kuala Lumpur',1200,'rent','Master Room','Serviced Residence','Fully furnished','Any','Wi-Fi,Air-conditioning,Private bathroom,Pool,Gym,Parking','Attached bathroom, KL skyline view, walking distance to LRT Kerinchi and offices.','image.php?id=4',12,2,0.5,250,3.111,101.665);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (2,'Budget single room, SS15 Subang Jaya','SS15, Subang Jaya','Selangor',480,'rent','Single Room','Apartment','Partially furnished','Female','Wi-Fi,Washing machine,Near MRT/LRT,Near university','Perfect for students — Taylor''s and INTI nearby. Quiet female-only unit.','image.php?id=7',6,1,0.5,150,3.076,101.586);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (2,'Big master room, Mont Kiara expat area','Mont Kiara','Kuala Lumpur',1500,'rent','Master Room','Condominium','Fully furnished','Any','Wi-Fi,Air-conditioning,Private bathroom,Pool,Gym,Parking,Security / guarded','Premium condo with full facilities, balcony, covered parking included.','image.php?id=10',12,2.5,0.5,300,3.166,101.651);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (3,'Medium room in landed house, Petaling Jaya','SS2, Petaling Jaya','Selangor',600,'rent','Medium Room','Terrace House','Partially furnished','Male','Wi-Fi,Washing machine,Parking,Near food court','Quiet neighbourhood, famous SS2 food nearby, car porch parking available.','image.php?id=13',6,1,0.5,100,3.117,101.624);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (3,'Single room walk to Cyberjaya offices','Cyberjaya','Selangor',520,'rent','Single Room','Serviced Residence','Fully furnished','Any','Wi-Fi,Air-conditioning,Pool,Gym,Shuttle','Ideal for tech workers. Shuttle to major offices, utilities capped at RM50.','image.php?id=16',3,1,0.5,100,2.922,101.65);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (3,'Master room, Setia Alam with parking','Setia Alam','Selangor',850,'rent','Master Room','Double Storey House','Fully furnished','Any','Wi-Fi,Air-conditioning,Private bathroom,Parking,Garden','Spacious landed home near Setia City Mall. Includes one car park bay.','image.php?id=19',12,2,1,250,3.103,101.457);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (2,'Studio-style room, KLCC fringe','Kampung Baru','Kuala Lumpur',980,'rent','Studio','Apartment','Fully furnished','Any','Wi-Fi,Air-conditioning,Kitchenette,Near MRT/LRT','Own kitchenette and entrance. 10 min to KLCC, halal eateries downstairs.','image.php?id=22',6,1.5,0.5,200,3.166,101.705);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (3,'Female unit medium room, Wangsa Maju','Wangsa Maju','Kuala Lumpur',580,'rent','Medium Room','Condominium','Fully furnished','Female','Wi-Fi,Air-conditioning,Pool,Near MRT/LRT,Security / guarded','Female-only unit, 7 min walk to LRT Wangsa Maju, near AEON Big.','image.php?id=25',12,2,0.5,150,3.205,101.732);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (2,'Low-deposit single room, Kepong','Kepong','Kuala Lumpur',450,'rent','Single Room','Flat','Partially furnished','Male','Wi-Fi,Washing machine,Near bus stop','One month deposit only. Near Kepong market and bus routes.','image.php?id=28',1,1,0,50,3.21,101.638);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (2,'Renovated 3R2B condo, Cheras','Cheras','Kuala Lumpur',438000,'sale','Whole Unit','Condominium','Partially furnished','Any','Pool,Gym,Security / guarded,Parking,Near MRT/LRT','Freehold 1,012 sqft, new kitchen cabinets, 2 covered car parks.','image.php?id=31',0,0,0,0,3.085,101.748);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (3,'Corner-lot double storey, Setia Alam','Setia Alam','Selangor',795000,'sale','Whole Unit','Double Storey House','Unfurnished','Any','Garden,Parking,Gated guarded','22x75 corner with extra land, move-in condition.','image.php?id=34',0,0,0,0,3.103,101.457);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (2,'Compact studio, KLCC fringe (investor unit)','Kampung Baru','Kuala Lumpur',365000,'sale','Studio','Serviced Residence','Fully furnished','Any','Pool,Gym,Near MRT/LRT,Airbnb friendly','Tenanted at RM1.9k/mo, 5.9% gross yield, walk to LRT.','image.php?id=37',0,0,0,0,3.166,101.705);
INSERT INTO listings (owner_id,title,area,city,price,listing_type,room_type,property_type,furnishing,gender_pref,amenities,description,image,min_tenure,dep_months,util_months,fee_rm,lat,lng) VALUES (3,'Family apartment, Wangsa Maju','Wangsa Maju','Kuala Lumpur',420000,'sale','Whole Unit','Apartment','Partially furnished','Any','Near MRT/LRT,Security / guarded,Playground','3 rooms 2 baths, 950 sqft, near AEON Big and LRT.','image.php?id=40',0,0,0,0,3.205,101.732);

-- ---- default moderation setting ----
INSERT INTO settings (name, value) VALUES ('report_threshold', '3');
